#!/usr/bin/env node
// Prepare and launch one Taskforce CLI via a terminal backend.
// v0.2: no roles, no modes, no role config. Accepts --cli and --model directly.

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';
import { spawnSync } from 'node:child_process';
import { normalizeModel, parseArgs } from './protocol_lib.mjs';
import { resolveCmuxPath } from './doctor.mjs';

function run(command) {
  const r = spawnSync(command[0], command.slice(1), {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  });
  if (r.status !== 0) {
    const msg = (r.stderr || r.stdout || '').trim();
    process.stderr.write(msg + '\n');
    process.exit(1);
  }
  return (r.stdout || '').trim();
}

// Canonical cmux workspace creation.
export function terminalCommand(project, nodeId, taskStem, launcherPath) {
  const cmuxPath = resolveCmuxPath();
  if (!cmuxPath) {
    process.stderr.write('cmux_not_installed\n');
    process.exit(1);
  }
  return [cmuxPath, 'workspace', 'create', '--name', `${nodeId}: ${taskStem}`,
    '--cwd', String(project), '--command', String(launcherPath)];
}

function shQuote(part) {
  const s = String(part);
  if (s === '') return "''";
  if (/^[A-Za-z0-9_@%+=:,./-]+$/.test(s)) return s;
  return "'" + s.replace(/'/g, "'\"'\"'") + "'";
}

function shJoin(parts) {
  return parts.map((p) => shQuote(p)).join(' ');
}

function expandUser(p) {
  if (typeof p !== 'string') return p;
  if (p === '~') return os.homedir();
  if (p.startsWith('~/')) return path.join(os.homedir(), p.slice(2));
  return p;
}

// Sanitize PATH for worker CLI processes.
//
// taskforce runs inside a host (e.g. WorkBuddy desktop) that may inject CLI-
// specific shell shims (safe-bin/rm, safe-bin/unlink, ...) into PATH. These
// shims require host-private env vars to function; without them they fail
// closed and break worker startup (e.g. codebuddy's PluginManager file
// cleanup is routed through such a shim and fails when the env is absent).
//
// Worker CLIs are CLI-agnostic execution units and must not inherit host
// shim infrastructure. Remove any PATH entry whose rm/unlink/rmdir is a
// `#!` script (a shim) rather than a native binary. Real system dirs
// (/bin, /usr/bin, ...) hold native binaries and are always kept.
const FALLBACK_WORKER_PATH = '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin';

function sanitizePathForWorker(rawPath) {
  if (!rawPath) return FALLBACK_WORKER_PATH;
  const SHIMMED_UTILITIES = ['rm', 'unlink', 'rmdir'];
  const MAX_SHIM_SIZE = 4096; // shims are tiny shell scripts; real bins are larger
  const sanitized = rawPath
    .split(path.delimiter)
    .filter((dir) => {
      if (!dir) return true;
      for (const util of SHIMMED_UTILITIES) {
        const utilPath = path.join(dir, util);
        try {
          const stat = fs.statSync(utilPath);
          if (!stat.isFile() || stat.size > MAX_SHIM_SIZE) continue;
          // Detect shebang — a `#!` prefix marks a script shim.
          const fd = fs.openSync(utilPath, 'r');
          const buf = Buffer.alloc(2);
          fs.readSync(fd, buf, 0, 2, 0);
          fs.closeSync(fd);
          if (buf.toString('utf8') === '#!') {
            return false; // script shim — drop this directory
          }
        } catch {
          // file missing or unreadable — keep checking other utilities
        }
      }
      return true;
    })
    .join(path.delimiter);
  // Every entry looking like a shim directory would leave the worker with no
  // PATH at all, which breaks the launcher before the CLI even starts.
  return sanitized || FALLBACK_WORKER_PATH;
}

export function main(argv) {
  const args = parseArgs(argv || process.argv.slice(2), {
    flags: ['execute'],
    valued: ['project-dir', 'task-file', 'orchestrator-dir', 'skill-dir', 'workflow-id', 'node-id', 'cli', 'model'],
  });
  if (!args['project-dir'] || !args['task-file'] || !args['workflow-id'] || !args['node-id'] || !args['cli']) {
    process.stderr.write(
      'usage: prepare_terminal_launch.mjs --project-dir --task-file --workflow-id --node-id --cli [--model --execute]\n'
    );
    return 2;
  }

  const project = path.resolve(expandUser(args['project-dir']));
  const skillDir = path.resolve(
    expandUser(args['skill-dir'] || path.join(path.dirname(new URL(import.meta.url).pathname), '..'))
  );
  const orchRel = args['orchestrator-dir'] || '.taskforce';
  const cli = String(args.cli || '').trim();
  const model = normalizeModel(args.model);
  const workflowId = args['workflow-id'];
  const nodeId = args['node-id'];

  if (!cli) {
    process.stderr.write('cli is required\n');
    return 1;
  }

  let taskPath = args['task-file'];
  if (!path.isAbsolute(taskPath)) taskPath = path.join(project, taskPath);
  taskPath = path.resolve(taskPath);

  const taskId = path.basename(taskPath, path.extname(taskPath));

  // The prompt is generated by agent_runner.mjs (the minimal prompt).
  // Create a thin launcher that cmux executes automatically as the surface's
  // initial command. It is not a user-facing script: it writes launch evidence
  // inside the cmux environment, then execs the selected CLI into the same PTY.

  const launcherPath = path.join(
    project,
    orchRel,
    'launchers',
    `${taskId}-${nodeId}.sh`
  );
  fs.mkdirSync(path.dirname(launcherPath), { recursive: true });

  const runnerCmd = [
      process.execPath,
      path.join(skillDir, 'scripts', 'agent_runner.mjs'),
      '--prepare',
      '--project-dir', String(project),
      '--orchestrator-dir', orchRel,
      '--task-file', String(taskPath),
      '--workflow-id', workflowId,
      '--node-id', nodeId,
      '--cli', cli,
    ];
  if (model !== null) runnerCmd.push('--model', String(model));
  const runnerArray = shJoin(runnerCmd);
  // Worker CLIs must run on a clean PATH: the host process may carry CLI-
  // specific shims (e.g. safe-bin) that fail without host-private env vars.
  // Strip any PATH directory whose rm/unlink/rmdir is a script shim, and
  // fully override PATH (do not append the launcher shell's $PATH, which is
  // the same polluted host environment).
  const sanitizedPath = sanitizePathForWorker(process.env.PATH || '');
  const launcher =
      '#!/usr/bin/env bash\n' +
      'set -euo pipefail\n' +
      `cd ${shQuote(project)}\n` +
      `export PATH=${shQuote(sanitizedPath)}\n` +
      '# Step 1: Prepare protocol evidence and generate TUI exec snippet.\n' +
      `eval "$(${runnerArray})"\n` +
      '# Step 2: Source the TUI exec snippet to replace this shell with\n' +
      '# the CLI directly — no Node child-process nesting.\n' +
      'source "$TUI_EXEC_PATH"\n';
  fs.writeFileSync(launcherPath, launcher, 'utf8');
  fs.chmodSync(launcherPath, 0o755);

  const backendCommand = terminalCommand(project, nodeId, taskId, launcherPath);
  const printable = shJoin(backendCommand);

  if (!args.execute) {
    process.stdout.write(`launcher_file=${launcherPath}\n`);
    process.stdout.write('terminal_backend=cmux\n');
    process.stdout.write(`cli=${cli}\n`);
    process.stdout.write(`model=${model === null ? 'null' : JSON.stringify(model)}\n`);
    process.stdout.write(printable + '\n');
    return 0;
  }

  const r = spawnSync(backendCommand[0], backendCommand.slice(1), { stdio: 'inherit' });
  if (r.status !== 0) {
    return r.status === null ? 1 : r.status;
  }
  process.stdout.write(`launched_node=${nodeId}\n`);
  process.stdout.write(`launcher_file=${launcherPath}\n`);
  process.stdout.write('terminal_backend=cmux\n');
  process.stdout.write(`cli=${cli}\n`);
  process.stdout.write(`model=${model === null ? 'null' : JSON.stringify(model)}\n`);
  return 0;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  process.exit(main());
}
